name: ci_build

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_build.yml"


jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build gfortran libopenmpi-dev openmpi-bin


    - run: cmake --preset default -Darith=d
    - run: cmake --build --preset default
    - run: ctest --preset default

    - run: cmake --install build

    # - run: cmake -S build/_deps/mumps-src/examples -B build-ex
    # - run: cmake --build build-ex --parallel
    # - run: ctest --test-dir build-ex
