name: ci_build

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_build.yml"


jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends libopenmpi-dev openmpi-bin


    - run: cmake -B build -Darith=d -Dautobuild:BOOL=on --install-prefix=${HOME}
    - run: cmake --build build --parallel
    - run: ctest --test-dir build --preset default

    - run: cmake --install build
