name: ci_mac
env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  FC: gfortran-11

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_mac.yml"


jobs:

  mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - run: brew install gcc lapack scalapack open-mpi

    - run: cmake --preset default -Darith=d
    - run: cmake --build --preset default
    - run: ctest --preset default

    - run: cmake --install build
