name: ci_mac
env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CMAKE_BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja
  FC: gfortran-11

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_mac.yml"


jobs:

  mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - run: brew install ninja gcc lapack scalapack open-mpi

    - name: configure release
      run: cmake -B build -Darith=d --install-prefix=${HOME}
    - name: build release
      run: cmake --build build --parallel
    - name: test release
      run: ctest --test-dir build --preset default

    - name: install package
      run: cmake --install build


    - name: configure example
      run: cmake -S examples -B examples/build -DMUMPS_ROOT=${HOME}
    - name: build example
      run: cmake --build examples/build || cmake --build examples/build -v
    - name: test example
      run: ctest --test-dir examples/build --output-on-failure
