name: ci_windows

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"


jobs:

  windows:
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: "MinGW Makefiles"

    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build -Darith=d -Dparallel:BOOL=false
    - run: cmake --build build
    - run: ctest --test-dir build --preset default
